** **CLASSIFICATION OF FLOWER** USING **K-NEAREST** **ALGORITHM** **

In [80]:
#importing the datasets from sklearn and we are defining a function[load_iris()] which loads the datasets in variable[iris_dataset] 
from sklearn.datasets import load_iris
iris_dataset = load_iris()


In [81]:
#dataset is in the dict() form ,so we r gonna view the keys
print("Keys of dataset: \n{}".format(iris_dataset.keys()))

Keys of dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [ ]:
##Now , we are gonna see values of each keys ;
#Values of key('DESCR') : it contains the description of the dataset
#and we will slice the (descr) from [0th - n(last)th character] 
print(iris_dataset['DESCR'][:]+ "\n....")

In [83]:
#Values of key('target_names') : as the name suggests , it contains the target names or labels
print("Target names:") 
print(iris_dataset['target_names'])

Target names:
['setosa' 'versicolor' 'virginica']


In [84]:
#Values of key('feature_names'): contains the ways the data is distributed
print("Feature Names:")
print(iris_dataset['feature_names'])

Feature Names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [85]:
#Values and type of key('data'):type of data is noted here coz we need to know what kind of data we r gonna work [numpy comes into attack ;)]
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


In [86]:
#Shape of data is (row,column)
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


In [87]:
# and now the data itself 
print("First five rows of data: \n{}".format(iris_dataset['data'
][:5]))

First five rows of data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [88]:
#Target,shape and type of key(target) 
print("Types of target: {}".format(type(iris_dataset['target'])))

Types of target: <class 'numpy.ndarray'>


In [89]:
print("Shape of Target: {}".format(iris_dataset['target'].shape))

Shape of Target: (150,)


In [90]:
print("Target: {}".format(iris_dataset['target']))

Target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [91]:
##From now we will be training the data (that's what machine learning is after all)
#we will import trainer who will split the test from sklearn package 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

In [92]:
#So we shall see the shape after spliting them for training and testing
print("X-train shape: {}".format(X_train.shape))
print("Y-train shape: {}".format(y_train.shape))
print("X-test shape: {}".format(X_test.shape))
print("Y-test shape: {}".format(y_test.shape))

X-train shape: (112, 4)
Y-train shape: (112,)
X-test shape: (38, 4)
Y-test shape: (38,)


In [93]:
#We are inheriting the ML model and gonna implement the the K-nearest classifier algo.
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors = 1)

In [94]:
#Now let's provide the model the trainer kit so that it would learn and fit 
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [95]:
#It's testing time ; lets initialise the new variable:
X_new = np.array([[5,2.9,3,2.2]])
print("X-new shape : {}".format(X_new.shape))

X-new shape : (1, 4)


In [96]:
#Let's give a small test:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Prediction target_name: {}".format(iris_dataset['target_names'][prediction]))

Prediction: [1]
Prediction target_name: ['versicolor']


In [97]:
# Let's evaluate our model on our test data
y_predict = knn.predict(X_test)
print("Test set predictions: \n {}".format(y_predict)) 

Test set predictions: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [98]:
# Our model's prediction has come and let's check it out with our test answer's value that we have saved 
print("test set score: {}".format(np.mean(y_predict==y_test)))

test set score: 0.9736842105263158


That's it . Our model has scored 0.973/1 ; We have scored a marvallous credit
